In [2]:
#0-d array
import numpy as np
arr = np.array(4)
print(arr)

4


In [3]:
#1-d array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
#2-d array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
#3-d array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [19]:
#Dimenison display
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
#Array indexing
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])

2


In [21]:
#Array addition
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [23]:
#Access 2-d array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("2nd elemnt on the first row:",arr[0,1])

2nd elemnt on the first row: 2


In [33]:
#Slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[:5])
print(arr[:])
print(arr[4:])

#Negative slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

# Step slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

#Return every other element
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5 6 7]
[5 6 7]
[5 6]
[2 4]
[1 3 5 7]


In [34]:
#Slicing a 2-d arrays
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [39]:
#Create a 3*3 numpy array
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)


#1D array of 10 evenly spced valeus between 5 and 50
B= np.array([15,25,35,45])
print("1D array of 5 to 50:")
print(B)

#Convert a Pyhton list into Numpy array
list = [1,2,3,4]

arr = np.array(list)
print("list to array:")
print(arr)

#Reverse a 1d array
C = np.array([15,25,35,45])
print("reverse:")
print(C[::-1])

#3X3 Identity matrix
matrix = np.eye(3)
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1D array of 5 to 50:
[15 25 35 45]
list to array:
[1 2 3 4]
reverse:
[45 35 25 15]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
